/** App shell: collapsible sidebar, chat pane, welcome state, health badge. */

import { useEffect, useRef, useState } from "react";
import { Composer } from "./components/Composer";
import { CohereMark, MenuIcon } from "./components/Logo";
import { MessageRow } from "./components/Messages";
import { Sidebar } from "./components/Sidebar";
import { useChat } from "./useChat";

const SUGGESTIONS = [
  "Who was the second person to walk on the moon?",
  "What is the capital of Australia?",
  "Who wrote One Hundred Years of Solitude?",
];

function Welcome({ onPick }: { onPick: (query: string) => void }) {
  return (
    <div className="flex h-full flex-col items-center justify-center px-6 text-center">
      <CohereMark className="mb-5 h-12 w-12" />
      <h2 className="text-2xl font-semibold tracking-tight">Ask me anything</h2>
      <p className="mt-2 max-w-md text-sm leading-relaxed text-ink-dim">
        Answers are generated by Cohere and grounded in live Wikipedia searches, with sources and
        citations. Follow-ups remember the conversation.
      </p>
      <div className="mt-7 flex w-full max-w-md flex-col gap-2">
        {SUGGESTIONS.map((suggestion) => (
          <button
            key={suggestion}
            onClick={() => onPick(suggestion)}
            className="rounded-xl border border-line bg-panel px-4 py-2.5 text-sm text-ink-dim transition hover:border-accent/40 hover:text-ink"
          >
            {suggestion}
          </button>
        ))}
      </div>
    </div>
  );
}

function useHealth(): boolean | null {
  const [healthy, setHealthy] = useState<boolean | null>(null);
  useEffect(() => {
    fetch("/health")
      .then((response) => setHealthy(response.ok))
      .catch(() => setHealthy(false));
  }, []);
  return healthy;
}

export default function App() {
  const chat = useChat();
  const healthy = useHealth();
  const bottomRef = useRef<HTMLDivElement>(null);
  const [sidebarOpen, setSidebarOpen] = useState(
    () => typeof window !== "undefined" && window.innerWidth >= 768,
  );

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [chat.messages]);

  const closeOnMobile = () => {
    if (window.innerWidth < 768) setSidebarOpen(false);
  };

  const title = chat.messages.find((message) => message.role === "user")?.text ?? "New conversation";

  return (
    <div className="relative flex h-full overflow-hidden">
      <div
        onClick={() => setSidebarOpen(false)}
        className={`fixed inset-0 z-30 bg-black/60 transition-opacity duration-200 md:hidden ${
          sidebarOpen ? "opacity-100" : "pointer-events-none opacity-0"
        }`}
      />

      <Sidebar
        open={sidebarOpen}
        conversations={chat.conversations}
        activeId={chat.conversationId}
        historyError={chat.historyError}
        apiKey={chat.apiKey}
        onSelect={(id) => {
          void chat.loadConversation(id);
          closeOnMobile();
        }}
        onNewChat={() => {
          chat.newChat();
          closeOnMobile();
        }}
        onClose={() => setSidebarOpen(false)}
        onSetApiKey={chat.setApiKey}
      />

      <main className="relative flex min-w-0 flex-1 flex-col">
        <div className="pointer-events-none absolute -top-32 left-1/2 h-72 w-[42rem] max-w-full -translate-x-1/2 rounded-full bg-accent/8 blur-3xl" />

        <header className="flex items-center gap-3 border-b border-line px-3 py-3 md:px-5">
          <button
            onClick={() => setSidebarOpen((open) => !open)}
            aria-label="Toggle sidebar"
            className="rounded-lg p-1.5 text-ink-dim transition hover:bg-panel-2 hover:text-ink"
          >
            <MenuIcon className="h-5 w-5" />
          </button>
          <p className="min-w-0 flex-1 truncate text-sm text-ink-dim">{title}</p>
          <div className="flex shrink-0 items-center gap-2.5 text-xs text-ink-dim">
            {chat.model && (
              <span className="hidden rounded-full border border-line px-2.5 py-1 sm:inline">
                {chat.model}
              </span>
            )}
            <span className="flex items-center gap-1.5">
              <span
                className={`h-2 w-2 rounded-full ${
                  healthy == null ? "bg-zinc-500" : healthy ? "bg-emerald-400" : "bg-red-400"
                }`}
              />
              <span>{healthy == null ? "checking" : healthy ? "online" : "offline"}</span>
            </span>
          </div>
        </header>

        {chat.messages.length === 0 ? (
          <Welcome onPick={(query) => void chat.send(query)} />
        ) : (
          <div className="flex-1 overflow-y-auto">
            <div className="mx-auto w-full max-w-3xl space-y-6 px-4 py-8 md:px-6">
              {chat.messages.map((message) => (
                <MessageRow key={message.id} message={message} />
              ))}
              <div ref={bottomRef} />
            </div>
          </div>
        )}

        <Composer
          sending={chat.sending}
          onSend={(query) => void chat.send(query)}
          onStop={chat.stop}
        />
      </main>
    </div>
  );
}
